In [1]:
import pandas as pd

In [2]:
data=pd.read_excel("/content/drive/MyDrive/Learning/folders/my data.xlsx")

In [3]:
data.head(5)

,Patient_ID,Visit_Date,Gender,Age,Department,Diagnosis_Category,Bill_Amount
0,PAT00160,2025-08-06,Female,74,NaN,Routine Checkup,252.79
1,PAT00156,2025-12-30,Male,5,Maternity,Cardiovascular,189.10
2,PAT00188,2025-11-10,NaN,68,Emergency,Routine Checkup,126.17
3,PAT00073,2025-10-02,Male,82,Outpatient,Infection,44.56
4,PAT00199,2026-05-21,Female,46,Pediatrics,Maternal,74.29

In [4]:
data.tail(5)

,Patient_ID,Visit_Date,Gender,Age,Department,Diagnosis_Category,Bill_Amount
295,PAT00200,2025-09-27,Male,84,Internal Medicine,Routine Checkup,238.03
296,PAT00169,2025-12-23,Male,13,Emergency,Cardiovascular,119.04
297,PAT00221,2026-04-06,Female,25,Outpatient,Routine Checkup,66.20
298,PAT00084,2025-05-15,Male,61,Emergency,routine checkup,117.85
299,PAT00110,NaT,Female,79,Outpatient,Routine Checkup,83.84

In [8]:
data.sample(10)

,Patient_ID,Visit_Date,Gender,Age,Department,Diagnosis_Category,Bill_Amount
140,PAT00159,2025-06-15,Female,49,Pediatrics,Respiratory,49.21
70,PAT00242,2025-03-20,Female,83,Pediatrics,Respiratory,43.41
108,PAT00050,2025-01-02,Female,47,Outpatient,NaN,51.95
172,PAT00058,2025-09-08,Male,11,Outpatient,Maternal,68.76
251,PAT00059,2025-05-21,NaN,34,Outpatient,Routine Checkup,58.76
160,PAT00189,2025-08-16,Female,8,Outpatient,Maternal,94.88
142,PAT00231,2026-06-21,Male,60,Outpatient,Infection,90.94
191,PAT00214,2025-11-23,Male,32,Pediatrics,Respiratory,38.05
289,PAT00157,2026-02-05,Male,36,Internal Medicine,Cardiovascular,217.69
227,PAT00237,2025-07-20,Female,2,Pediatrics,Routine Checkup,111.93

In [7]:
data.shape

(300, 7)

In [10]:
data.columns

Index(['Patient_ID', 'Visit_Date', 'Gender', 'Age', 'Department',
       'Diagnosis_Category', 'Bill_Amount'],
      dtype='object')

In [11]:
data.index

RangeIndex(start=0, stop=300, step=1)

In [12]:
data.dtypes

Patient_ID                    object
Visit_Date            datetime64[ns]
Gender                        object
Age                           object
Department                    object
Diagnosis_Category            object
Bill_Amount                  float64
dtype: object

In [13]:
data.index

RangeIndex(start=0, stop=300, step=1)

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_ID          285 non-null    object
 1   Visit_Date          284 non-null    datetime64[ns]
 2   Gender              284 non-null    object
 3   Age                 284 non-null    object
 4   Department          284 non-null    object
 5   Diagnosis_Category  280 non-null    object
 6   Bill_Amount         281 non-null    float64
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 16.5+ KB

In [16]:
data.describe()

                          Visit_Date  Bill_Amount
count                            284   281.000000
mean   2025-09-25 06:05:04.225352192   192.323132
min              2025-01-01 00:00:00    -9.000000
25%              2025-05-05 12:00:00    66.170000
50%              2025-09-29 12:00:00    96.100000
75%              2026-02-19 18:00:00   203.040000
max              2026-07-26 00:00:00  1171.520000
std                              NaN   232.528236